"""Exact v0 names shared by the SWE and Data/ML workstreams."""

from pydantic import BaseModel

from founderlookup import domain


def test_v0_contract_version_identifiers_are_frozen() -> None:
    assert {
        "contract": domain.CONTRACT_SCHEMA_VERSION,
        "knowledge_value": domain.KNOWLEDGE_VALUE_SCHEMA_VERSION,
        "lifecycle": domain.LIFECYCLE_SCHEMA_VERSION,
        "evidence_graph": domain.EVIDENCE_GRAPH_SCHEMA_VERSION,
        "discovery": domain.DISCOVERY_SCHEMA_VERSION,
        "acquisition": domain.ACQUISITION_SCHEMA_VERSION,
        "query_plan": domain.OPPORTUNITY_QUERY_PLAN_SCHEMA_VERSION,
        "founder_score": domain.FOUNDER_SCORE_SCHEMA_VERSION,
        "claim_trust": domain.CLAIM_TRUST_SCHEMA_VERSION,
        "axis": domain.AXIS_ASSESSMENT_SCHEMA_VERSION,
        "assessment": domain.ASSESSMENT_ENVELOPE_SCHEMA_VERSION,
        "readiness": domain.DECISION_READINESS_SCHEMA_VERSION,
        "memo": domain.INVESTMENT_MEMO_SCHEMA_VERSION,
        "recommendation": domain.RECOMMENDATION_SCHEMA_VERSION,
        "decision": domain.HUMAN_DECISION_SCHEMA_VERSION,
        "run": domain.PIPELINE_RUN_SCHEMA_VERSION,
    } == {
        "contract": "vc-brain.v0",
        "knowledge_value": "knowledge-value.v0",
        "lifecycle": "lifecycle.v0",
        "evidence_graph": "evidence-graph.v0",
        "discovery": "discovery.v0",
        "acquisition": "acquisition.v0",
        "query_plan": "opportunity-query-plan.v0",
        "founder_score": "founder-score.v0",
        "claim_trust": "claim-trust.v0",
        "axis": "axis-assessment.v0",
        "assessment": "assessment-envelope.v0",
        "readiness": "decision-readiness.v0",
        "memo": "investment-memo.v0",
        "recommendation": "recommendation.v0",
        "decision": "human-decision.v0",
        "run": "pipeline-run.v0",
    }


def test_v0_lifecycle_vocabularies_are_frozen() -> None:
    assert tuple(value.value for value in domain.OutboundCandidateStatus) == (
        "discovered",
        "preliminary_assessment",
        "ready_for_activation",
        "activated",
        "contacted",
        "applied",
        "closed",
    )
    assert tuple(value.value for value in domain.ApplicationStatus) == (
        "received",
        "ingesting",
        "ready_for_screening",
        "linked_to_screening_case",
        "withdrawn",
        "failed",
    )
    assert tuple(value.value for value in domain.ScreeningCaseStatus) == (
        "first_pass",
        "screening",
        "diligence",
        "readiness_review",
        "blocked",
        "decision_ready",
        "decided",
        "closed",
    )
    assert tuple(value.value for value in domain.DecisionReadinessStatus) == (
        "not_evaluated",
        "blocked",
        "ready",
        "ready_with_accepted_risk",
    )
    assert tuple(value.value for value in domain.PipelineRunStatus) == (
        "queued",
        "running",
        "succeeded",
        "partially_succeeded",
        "failed",
    )


def test_v0_model_field_names_are_frozen() -> None:
    expected: dict[type[BaseModel], set[str]] = {
        domain.KnowledgeValue: {
            "schema_version",
            "state",
            "value",
            "reason",
            "evidence_ids",
            "alternatives",
        },
        domain.SourceArtifact: {
            "schema_version",
            "source_artifact_id",
            "artifact_series_id",
            "artifact_version_id",
            "version_number",
            "previous_source_artifact_id",
            "kind",
            "source_category",
            "classification",
            "origin_locator",
            "display_name",
            "media_type",
            "content_sha256",
            "retrieved_at",
            "source_event_time",
            "collection_operation_id",
            "availability",
        },
        domain.Observation: {
            "schema_version",
            "observation_id",
            "observation_version_id",
            "source_artifact_id",
            "subject",
            "predicate",
            "observed_value",
            "locator",
            "retrieved_at",
            "source_event_time",
            "extraction_method",
            "extraction_version",
            "verification_state",
        },
        domain.Claim: {
            "schema_version",
            "claim_id",
            "claim_version_id",
            "subject",
            "predicate",
            "statement",
            "status",
            "origin",
            "as_of",
            "created_at",
            "supporting_evidence_ids",
            "counter_evidence_ids",
            "trust",
        },
        domain.Evidence: {
            "schema_version",
            "evidence_id",
            "claim_id",
            "source_artifact_id",
            "observation_id",
            "stance",
            "locator",
            "collected_at",
            "source_event_time",
            "availability",
        },
        domain.DiscoveryRequest: {
            "schema_version",
            "request_id",
            "query_plan_id",
            "requested_at",
            "retrieval_requests",
        },
        domain.DiscoveryResult: {
            "schema_version",
            "result_id",
            "request_id",
            "status",
            "completed_at",
            "leads",
            "failures",
            "usage",
        },
        domain.AcquisitionRequest: {
            "schema_version",
            "acquisition_request_id",
            "discovery_lead_id",
            "original_url",
            "requested_at",
            "classification",
            "allowed_media_types",
            "max_bytes",
            "timeout_seconds",
        },
        domain.AcquisitionResult: {
            "schema_version",
            "result_id",
            "acquisition_request_id",
            "original_url",
            "status",
            "completed_at",
            "content",
            "media_type",
            "content_sha256",
            "source_event_time",
            "failure",
        },
        domain.OpportunityQueryPlan: {
            "schema_version",
            "query_plan_id",
            "query_plan_version_id",
            "supersedes_query_plan_version_id",
            "raw_query",
            "planning_mode",
            "planner_version",
            "state",
            "criteria",
            "retrieval_requests",
            "unresolved_phrases",
            "semantic_rerank",
            "max_results",
            "created_at",
        },
        domain.FounderScoreSnapshot: {
            "schema_version",
            "snapshot_id",
            "snapshot_version_id",
            "founder_id",
            "score_policy_version",
            "as_of",
            "score",
            "factors",
            "coverage",
            "uncertainty",
            "provisional",
        },
        domain.ClaimTrustScore: {
            "schema_version",
            "state",
            "trust_policy_version",
            "score",
            "factors",
            "reason",
        },
        domain.AssessmentEnvelope: {
            "schema_version",
            "assessment_id",
            "assessment_version_id",
            "identity",
            "versions",
            "input_snapshot_id",
            "input_snapshot_as_of",
            "coverage",
            "deterministic_results",
            "founder_score",
            "axes",
            "claim_ids",
            "evidence_ids",
            "contradictions",
            "diligence_actions",
            "decision_readiness",
            "memo",
            "recommendation",
            "run_id",
            "created_at",
            "human_decision_ids",
        },
        domain.DecisionReadiness: {
            "schema_version",
            "readiness_id",
            "readiness_version_id",
            "screening_case_id",
            "policy_version",
            "evaluated_at",
            "status",
            "checks",
            "blockers",
            "accepted_risks",
        },
        domain.InvestmentMemo: {
            "schema_version",
            "memo_id",
            "memo_version_id",
            "opportunity_id",
            "screening_case_id",
            "assessment_id",
            "run_id",
            "thesis_version",
            "evidence_as_of",
            "generated_at",
            "sections",
        },
        domain.Recommendation: {
            "schema_version",
            "recommendation_id",
            "recommendation_version_id",
            "subject",
            "assessment_id",
            "policy_version",
            "action",
            "reasons",
            "next_actions",
            "created_at",
        },
        domain.Decision: {
            "schema_version",
            "decision_id",
            "screening_case_id",
            "opportunity_id",
            "assessment_id",
            "memo_id",
            "reviewed_recommendation_id",
            "disposition",
            "actor_id",
            "rationale",
            "decided_at",
        },
        domain.PipelineRun: {
            "schema_version",
            "run_id",
            "kind",
            "status",
            "versions",
            "input_snapshot_id",
            "input_snapshot_as_of",
            "queued_at",
            "started_at",
            "completed_at",
            "stages",
            "accepted_output_ids",
            "failures",
            "retry_of_run_id",
            "attempt",
        },
    }

    for model, fields in expected.items():
        assert set(model.model_fields) == fields, model.__name__
